### ISSUE TITLE
Generalization of triangle

### ISSUE THREAD

**Issue by hauswirth** [LuCEresearchlab/pytamaro#10]
[`triangle(side: float, color: Color) -> Graphic`](https://pytamaro.readthedocs.io/en/stable/English/primitives.html#pytamaro.primitives.triangle) produces an equilateral triangle. Currently we have no way to create other kinds of triangles. This is severely limiting. Most problematic is the absence of right-angled triangles, which are prevalent in graphics. However, we should not just add right-angled triangles, but move to a general triangle function, ideally so there is only one function, and that that function takes the parameters (angles, side lengths) that are most often useful.

### References

The [Racket Image Teachpack](https://docs.racket-lang.org/teachpack/2htdpimage.html#%28def._%28%28lib._2htdp%2Fimage..rkt%29._triangle%29%29) provides an exhaustive set of functions (all side/angle combinations, plus the special cases of equilateral, right, and isosceles):

* triangle
* right-triangle
* isosceles-triangle
* triangle/sss
* triangle/ass
* triangle/sas
* triangle/ssa
* triangle/aas
* triangle/asa
* triangle/saa

This is convenient for the experienced programmer, because for any use case there already is the matching function. It can be overwhelming for the novice, though, and it deprives the novice from developing the structure of the space of possible triangle functions themselves (if so desired).

The [Diagrams library](https://archives.haskell.org/projects.haskell.org/diagrams/) is structured a bit differently: they provide equilateral triangles under [regular polygons](https://diagrams.github.io/haddock/diagrams-lib/Diagrams-TwoD-Shapes.html#g:2), and they provide various general ways to create [polygons](https://diagrams.github.io/haddock/diagrams-lib/Diagrams-TwoD-Polygons.html).

### Suggestion

I suggest to **replace** the existing `triangle` function with the following:

`triangle(angle: float, side1: float, side2: float, color: Color) -> Graphic`

```
      side1
angle _____
       \  |
  side2 \ |
         \|
```

The function should produce a triangle that is rotated the same way a `circular_sector` is. This way triangles can be composed into a rotational graphic (e.g., to create a regular convex polygon) the same way circular sectors can be.

The function should produce a triangle with the pinning position set into its centroid; this would allow composing triangles over their centroids, e.g., to create a triangle outline by overlaying a smaller onto a larger triangle. Note that the user of a triangle always can explicitly pin a triangle at the point of the given angle, which can be found with `pin("left", "middle" t)`.

### Advantages

This function allows the creation of any kind of triangle.

This allows users to write their own specialized triangle functions, if needed, or if desired for educational purposes:

```python
def equilateral_triangle(side: float, color: Color) -> Graphic:
  return triangle(60, side, side, color)

def isosceles_triangle(angle: float, side: float, color: Color) -> Graphic:
  return triangle(angle, side, side, color)

def right_triangle(side1: float, side2: float, color: Color) -> Graphic:
  return triangle(90, side1, side2, color)
```

### Drawbacks

This is a breaking change: any code using the existing `triangle` function will need to be rewritten (or use a user-created `equilateral_triangle` function):

```python
# Existing code
triangle(side, color)

# Rewrite to:
triangle(60, side, side, color)
```

**Comment by lucach** [comment]
I like this proposal!

> Note that the user of a triangle always can explicitly pin a triangle at the point of the given angle, which can be found with pin("left", "middle" t).

Shouldn't it be top-left, looking at the ASCII diagram? 

> This is a breaking change: any code using the existing triangle function will need to be rewritten

I'm a bit worried by these API breaking changes (this one, plus at least the new `pin` function). We should probably release them together, so that this does not become a "new-version-always-break-things" library.
