### ISSUE TITLE
German localization for version 0.4.0

### ISSUE THREAD

**Issue by lucach** [LuCEresearchlab/pytamaro#13]
We're about to release version 0.4.0. This version introduces a number of API breaking changes. [See the detailed CHANGELOG](https://github.com/LuCEresearchlab/pytamaro/blob/main/CHANGELOG.md).

Both new docstrings and [the module containing error messages](https://github.com/LuCEresearchlab/pytamaro/blob/main/pytamaro/localization.py) would need a translation to German.

@hauswirth could you kindly go over it (and raise issues whenever you stumble on something that does not seem right?)

**Comment by hauswirth** [comment]
I'm wondering about the documentation for `Point`.

Instead of:
"Represents a point in 2-dimensional space."
"Rappresenta un punto nello spazio 2-dimensionale."

Shouldn't we talk about:
"Represents a point on a plane."

While the term "space" is more general, do we need this generality here?

**Comment by hauswirth** [comment]
The `save_graphic` documentation in Italian needs to be updated to include saving to SVG. 

Also, the English version mentions "(without extension)" in the `filename` parameter description. Should we just cut that, or should we write "(with extension)"?

---
    """
    Save a graphic to a file.
    Two file formats are supported: PNG (raster graphics) and SVG (vector graphics).
    The extension of the filename (either ".png" or ".svg") determines the format.

    Graphics with no area cannot be saved in the PNG format.

    When `debug` is `True`, adorns the visualization with useful information
    for debugging: a red border around the bounding box and a yellowish cross
    around the pinning position.

    :param filename: name of the file to create (without the extension)
    :param graphic: graphic to be saved
    :param debug: can be optionally set to `True` to overlay debugging
           information
    """
---
    """
    Salva una grafica come file PNG.

    Una grafica vuota non può essere salvata; quindi chiamare questa funzione
    con essa non produce alcun affetto.

    Quando `debug` è `True`, adorna la visualizzazione con informazioni utili
    per debugging: un bordo rosso attorno alla bounding box e una croce
    giallastra attorno al punto di fissaggio.

    :param nome_file: nome del file da creare (senza estensione)
    :param grafica: grafica da visualizzare
    :param debug: può facoltativamente essere impostato a `True` per
           sovrapporre informazioni di debug
    """
---

**Comment by lucach** [comment]
> Instead of: "Represents a point in 2-dimensional space." "Rappresenta un punto nello spazio 2-dimensionale."
> 
> Shouldn't we talk about: "Represents a point on a plane."
> 
> While the term "space" is more general, do we need this generality here?

Agreed. Italian: "Rappresenta un punto nel piano."

**Comment by lucach** [comment]
> Also, the English version mentions "(without extension)" in the `filename` parameter description. Should we just cut that, or should we write "(with extension)"?

Right, that's a leftover. I'd say either drop it or briefly mention "including the extension"  given that SVG/PNG is documented above.

**Comment by hauswirth** [comment]
`point_names.py`:

> Names of notable points ("Points of Interest") that can be used as pinning positions of a graphic.

What is the reason for including the term "Points of Interest"? Couldn't we just drop that?

I removed it from the German version.

**Comment by hauswirth** [comment]
Some of the documentation uses wording that implies mutability.

Although it may feel a bit awkward, it may make sense to refrain from such wording and to consistently describe functions as returning new things (instead of "changing" / "updating" things).

I wrote the German documentation so it does not imply mutable graphics.

**Comment by hauswirth** [comment]
In the `empty_graphic` documentation: "An empty graphic cannot be shown nor saved."

I suggest we remove this. This has nothing to do with the empty graphic, and everything with the IO functions. And the IO functions are where we now document this.

I removed it from the German documentation, but kept it in the English and Italian version for now.

**Comment by lucach** [comment]
> `point_names.py`:
> 
> > Names of notable points ("Points of Interest") that can be used as pinning positions of a graphic.
> 
> What is the reason for including the term "Points of Interest"? Couldn't we just drop that?
> 
> I removed it from the German version.

"Historical" leftover from the times we were discussing this between us and Fabio. It might be reused for the future when moving towards custom points, but I agree with the removal for now. Dropped it in EN and IT as well.

**Comment by lucach** [comment]
> In the `empty_graphic` documentation: "An empty graphic cannot be shown nor saved."
> 
> I suggest we remove this. This has nothing to do with the empty graphic, and everything with the IO functions. And the IO functions are where we now document this.
> 
> I removed it from the German documentation, but kept it in the English and Italian version for now.

I fully agree also on this one. It is again a leftover and is now even factually incorrect:
- `empty_graphic()` is not the only graphic that has **no area**, and this is now the deciding factor (a `0x200` rectangle would have the same issue)
- some "backends" (e.g., saving in SVG) support saving graphics with no area

**Comment by lucach** [comment]
> Some of the documentation uses wording that implies mutability.
> 
> Although it may feel a bit awkward, it may make sense to refrain from such wording and to consistently describe functions as returning new things (instead of "changing" / "updating" things).
> 
> I wrote the German documentation so it does not imply mutable graphics.

Agreed. I changed the docstrings for the various operations in the EN/IT versions, mimicking the ones in German.
