### ISSUE TITLE
Showing animations

### ISSUE THREAD

**Issue by lucach** [LuCEresearchlab/pytamaro#15]
There are several questions on how to design the output part of the API. Currently, PyTamaro has three functions:
- `show_graphic(graphic, debug)`
- `save_graphic(filename, graphic, debug)`
- `save_gif(filename, graphics, duration, loop)`

We could add `show_gif(filename, graphics, duration, loop)` and call it a day, but the design leaves me rather unsatisfied, mainly because of the duplication. How does this square with our minimalistic API design?

Some assorted ideas:
- Should we replace `*_gif` with `*_animation`, moving away from the format? (even though the format has become a de facto synonym with the concept...)
- Should we remove the ability to add hardcoded debug information?
- Should we introduce a `create_gif/create_animation` function that creates a value of a new type?
- Should we generalize even further the function `save` (which already supports `.svg` and `.png` depending on the extension) and add the capability of saving to `.gif` (perhaps even a graphic as a single frame, as the degenerate case)?
- Should we generalize the function `show`?

@hauswirth what are your thoughts on this? It could be also faster to discuss this in a meeting.

**Comment by hauswirth** [comment]
:smile: You should have had lunch with Igor and me today!!!

Here is the JTamaro IO library description:
[Interaction.pdf](https://github.com/LuCEresearchlab/pytamaro/files/11544605/Interaction.pdf)

Ignore the `print` methods, which are about printing `Pair` and `Sequence` objects I use throughout the course.

The rest goes through a three-level progression (à la HtDP):

1. (Static) Graphics
2. Film Strips and Animations
3. Interactions

The Film Strips & Animations level is about *sequences* of graphics. I introduce that *after* I introduce repetition. The methods take a `Sequence<Graphic>`.

As for the debug info: in JTamaro this can be enabled in the graphic viewer. By default the graphics are just shown as is, with the scene graph on their side, and you can select a node on the scene graph to show its outline, bounding box, bounding box points, and pinning position. (BTW: I like the way those are rendered in JTamaro: they look different from the contents of the graphic, and thus they are clearly distinguishable from the graphic itself. Also, they look like similar constructs in vector drawing programs.)

**Comment by lucach** [comment]
Good background information (I had already seen the Java documentation), but most of the questions raised above still remain valid. We should discuss them soon.

**Comment by lucach** [comment]
Implemented in d78d8fbcd38456541a2992f174b72a1bd67daeac. @hauswirth, could you kindly proofread the German docstrings/names I changed and patch any opprobrium?

**Comment by hauswirth** [comment]
Done minor edits in German doc in [5d5960b](https://github.com/LuCEresearchlab/pytamaro/commit/5d5960be03756ba89bef74b46b21b4ea7be7d275). Should be ready for release.
