### ISSUE TITLE
FileNotFoundError when saving .svg

### ISSUE THREAD

**Issue by hauswirth** [LuCEresearchlab/pytamaro#16]
While working on the PyTamaro Web `circles` activity, I had a directory that already contained a file `circle.svg`, and I tried to save a graphic named `circles.svg` (plural):

```python
#teacher-only
from pytamaro import ellipse, red, blue, green, show_graphic, save_graphic, above, beside, rectangle

def circle(diameter, color):
    return ellipse(diameter, diameter, color)

blue_circle = circle(100, blue)

#show_graphic(blue_circle)
#save_graphic('circle.svg', blue_circle)

circles = beside(
    above(
        above(
            circle(100, red), 
            rectangle(0, 20, red)
        ),
        circle(100, blue)
    ),
    circle(150, green)
)

show_graphic(circles)
save_graphic('circles.svg', circles)
```

Executing this cell in the Jupyter notebook within VS Code, I got the following error:

<img width="1920" alt="image" src="https://github.com/LuCEresearchlab/pytamaro/assets/583696/01623d4c-d501-4b43-8ff2-a69931434c90">

**Comment by hauswirth** [comment]
Happens with PyTamaro 0.5.0 on python 3.11.3

**Comment by hauswirth** [comment]
It didn't happen when running OUTSIDE the Jupyter notebook.

Reopening the Jupyter notebook made it go away.

I'm not sure what the problem was, but it could be that the Jupyter kernel was in a bad state (I think I got a different error before I ended up with the error I reported here).

**Comment by lucach** [comment]
It might be that the file was not actually fully flushed to the storage device. Hopefully a call to `fsync` should avoid this read-before-write situation (https://github.com/LuCEresearchlab/pytamaro/commit/e9fea5b0f0141858bd5d6a5bf9c50a721329d68a).
