### ISSUE TITLE
docs: Add link to pytamaro web site throughout

### ISSUE THREAD

**Issue by hauswirth** [LuCEresearchlab/pytamaro#17]
People may link straight to a specific page of the documentation (e.g., to https://pytamaro.readthedocs.io/en/stable/English/index.html).
Currently users who land on those pages won't learn about the many resources on the PyTamaro Web site (https://pytamaro.si.usi.ch/).

Could we add links to the PyTamaro web site on all documentation pages (header or footer or sidebar)?

**Comment by lucach** [comment]
I've added it to the sidebar (with the help of a sphinx extension), which seems to me the most prominent place. It is already live for the [`latest` version of the documentation](https://pytamaro.readthedocs.io/en/latest/).
