### ISSUE TITLE
Incorrect pinning position for 360 degree circular_sector

### ISSUE THREAD

**Issue by hauswirth** [LuCEresearchlab/pytamaro#19]
I fear that `circular_sector`, when drawing a 360-degree sector, has the wrong pinning position:

```python
from pytamaro import show_graphic, circular_sector, black
show_graphic(circular_sector(100, 350, black), True)
```

![image](https://github.com/LuCEresearchlab/pytamaro/assets/583696/201c257e-fcd3-47d3-9d33-f182797b5867)

```python
show_graphic(circular_sector(100, 360, black), True)
```

![image](https://github.com/LuCEresearchlab/pytamaro/assets/583696/11b08a52-a7f7-444d-ac67-b9ae469d4d51)

**Comment by lucach** [comment]
Fixed and added a test for this in https://github.com/LuCEresearchlab/pytamaro/commit/3775cbe4b967cee8b63787491f53ff011db028e9.

I'd release it when we have a couple of more changes, unless this is a deal-breaker for an activity, in which case I can do it right now (first on PyPI and then on `pytamaro-web`).
