### ISSUE TITLE
Rendering transparent area to SVG produces black

### ISSUE THREAD

**Issue by hauswirth** [LuCEresearchlab/pytamaro#20]
This appears black:

```python
save_graphic("bad.svg", rectangle(width, height, transparent))
```

Workaround: this appears transparent:

```python
save_graphic("ok.svg", overlay(rectangle(width, 0, transparent), rectangle(0, height, transparent)))
```

**Comment by hauswirth** [comment]
I encountered this here:

https://pytamaro.si.usi.ch/activities/luce/bellinzona-market-stall/en/v1

**Comment by hauswirth** [comment]
The contents of `bad.svg`:

```svg
<?xml version="1.0" encoding="utf-8" ?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="200" height="100" shape-rendering="crispEdges">
	<path d="M0 0L200 0L200 100L0 100L0 0Z"/>
</svg>
```

**Comment by hauswirth** [comment]
If I change the color of the rectangle, I get this svg:

```svg
<?xml version="1.0" encoding="utf-8" ?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="200" height="100" shape-rendering="crispEdges">
	<path fill="#DD4D3E" d="M0 0L200 0L200 100L0 100L0 0Z"/>
</svg>
```

So, the transparent graphic will lead to the absence of a `fill` attribute. And it seems that SVG renderers then assume the color is black.

**Comment by lucach** [comment]
I've looked into this a bit but I'm still unsure at which level this should be best fixed. A lethal mix of viewers' compliance, Skia SVG generation, and versions of the SVG spec...

Given that we are already hijacking the root `<svg>` element, we could add the `fill="none"` attribute to force a transparent background for all our SVGs.

**Comment by hauswirth** [comment]
Sounds like a good approach.

**Comment by lucach** [comment]
Turns out this issue is actually a subcase of #24. The workaround implemented above is actually problematic in other cases (as it changes the assumption that the default fill color is black).
