### ISSUE TITLE
Add __str__ methods to Graphic, Color, and Point classes

### ISSUE THREAD

**Issue by hauswirth** [LuCEresearchlab/pytamaro#23]
A user might want to print a `Graphic`, a `Color`, or a `Point`.

For example...

```python
print(rgb_color(255, 0, 128))
```

...outputs...

```
Color(color=Color4f(1, 0, 0.501961, 1))
```

This is confusing for learners.

The string being printed is produced by the `__str__` method of the corresponding class.

We want to produce a string that is more understandable for learners.

**Comment by lucach** [comment]
**(Note: requires #22 to be merged before, as the transition to dataclasses affects `__str__` as well.)**

There's a question of what that string representation should be. [Pyret mostly uses an expression that can be used to "construct" the value](https://pyret.org/docs/latest/_global_.html#%28part._~3cglobal~3e_to-repr%29), but I'm not entirely convinced this does not have drawbacks (in terms of the confusion between an expression and its value after evaluation).

**Comment by lucach** [comment]
Implemented in branch `repr`.

As per [Python's official documentation on `__repr__`](https://docs.python.org/3/reference/datamodel.html#object.__repr__), 

> Called by the [repr()](https://docs.python.org/3/library/functions.html#repr) built-in function to compute the “official” string representation of an object. If at all possible, this should look like a valid Python expression that could be used to recreate an object with the same value (given an appropriate environment). If this is not possible, a string of the form <...some useful description...> should be returned. The return value must be a string object. If a class defines [__repr__()](https://docs.python.org/3/reference/datamodel.html#object.__repr__) but not [__str__()](https://docs.python.org/3/reference/datamodel.html#object.__str__), then [__repr__()](https://docs.python.org/3/reference/datamodel.html#object.__repr__) is also used when an “informal” string representation of instances of that class is required.

Just two examples:

```sh
>>> from pytamaro import *
>>> compose(pin(top_left, rectangle(10, 1, red)), text("hi", "Arial", 10, black))
compose(pin(top_left, rectangle(10, 1, red)), text('hi', 'Arial', 10, black))

>>> from pytamaro.it import *
>>> rettangolo(10, 1, colore_rgb(255, 0, 0))
rettangolo(10, 1, rosso)
```

If that sounds good, I'll go ahead and merge.

**Comment by hauswirth** [comment]
To me this looks great!

**Comment by lucach** [comment]
Thanks, merged!
This should be helpful in several debugging/error-related scenarios.
