### ISSUE TITLE
text should produce error if specified font not available

### ISSUE THREAD

**Issue by hauswirth** [LuCEresearchlab/pytamaro#27]
Currently, if one calls `text` with the name of a font that is not available, it silently uses a fallback font.

I'd call this "the Scratch approach to errors". Never give errors, and do your best to handle a programmer's request. An ideal setup for implanting the "superbug" into students' heads.

Yes, it may be convenient. But I think it teaches the harmful lesson that it is ok, or even desirable, to swallow errors.

It also frustrates programmers (like me, but I suspect anyone who tries to use a specific font) by making it hard to debug things. One gets a graphic back from `text` no matter whether the font was found or not, and one has to painfully analyze that graphic to determine whether the glyphs come from the intended font or from some fallback font.

I recommend that the text function explicitly determines whether the requested font is available, and if it is not, that it produces a crisp and clear error message (ideally with a pointer to more information about fonts in PyTamaro).

I see that being strict in this case can lead to an up-front cost for teachers or learners using the PyTamaro library on their own computers, because there will be no easy way to produce text that "just works" no matter the platform and its installed fonts. If we deem this bad, then I suggest we define a special font name (like "DefaultFont") that will resolve to whatever font might be available (i.e., use the current behavior). This is similar to, e.g., Java, which defines some "logical fonts" ("Dialog", "DialogInput", "Serif", "SansSerif", "Monospaced") that are available anywhere (https://docs.oracle.com/javase/8/docs/api/java/awt/Font.html) and that map to some available "physical font". I think we should not do that in such detail (we can't guarantee that every platform on which PyTamaro will run has at least one Serif, SansSerif, and Monospaced font). However, we can assume that every platform has at least some font, and thus we could use a name like "DefaultFont" to be treated as "I don't care which font I will get, I just want to see that text rendered".

**Comment by lucach** [comment]
As a compromise solution, [826acdf](https://github.com/LuCEresearchlab/pytamaro/commit/826acdfd8db6f62b04e84750abe7d7d9357e83d2) introduces a warning message printed on `stderr` when `text` is called with a font that is "not available" (as determined by skia).

This is part of [pytamaro 0.6.1](https://github.com/LuCEresearchlab/pytamaro/blob/main/CHANGELOG.md#061---2023-12-05), already released.
