### ISSUE TITLE
Confusing output for show_graphic with multiple arguments

### ISSUE THREAD

**Issue by redelmann** [LuCEresearchlab/pytamaro#35]
I have been testing PyTamaro with high school students and, first of all, most do like it very much!

I somewhat frequently run into students trying to show two graphics at the same time mistakingly using `show_graphic` with two arguments.

I would have expected such calls to `show_graphic` to fail.
Instead, they display the first graphic with debug information overlayed.
Indeed, the second parameter of `show_graphic` (with default value `False`) controls whether debugging info is displayed, and apparently graphics are truthy.

As an improvement, I would suggest to raise an error the value of the parameter `debug` is a graphic.
The error message could even point the user in the right direction and hint at the different ways of combining graphics.

**Comment by hauswirth** [comment]
@redelmann , thanks a lot for the feedback!

I actually made this exact mistake this weekend myself. Not that I *wanted* to pass two arguments, but I ended up missing a compose call surrounding two expressions that produce a graphic when I quickly threw something together. My first impression when getting the debug graphic was confusion.

I think it would be great to dynamically check the type of the `debug` parameter value in `show_graphic` and `save_graphic` and to report a good error message. Similarly, in `show_animation` and `save_animation`, we could check the `duration` and `loop` parameters.

@lucach , do you see a reason not to do that?

**Comment by lucach** [comment]
Checks added in https://github.com/LuCEresearchlab/pytamaro/commit/e780fdc3a6e0c6f4230094072564d6e6f875af7f. Thanks for the suggestion! This is indeed a common problem, worsened by the lack of proper type-checking.

**Comment by lucach** [comment]
(Released as v0.7.1, if you need to use it immediately.)
