### ISSUE TITLE
Using apng for animations

### ISSUE THREAD

**Issue by frovaaa** [LuCEresearchlab/pytamaro#37]
This issue aims to test and potentially integrate the usage of the apng extension (using .png in practice) in replacement (or as a side option to maintain backward compatibility) of the currently used .gif when dealing with animations inside PyTamaro.

There is linked a [branch](https://github.com/LuCEresearchlab/pytamaro/tree/37-using-apng-for-animations) in which an initial integration has been done by replacing the .gif with .png only (cannot use .png anymore) and it seems to work fine, it also fixes some issues we encountered with transparent/black background while using the gif extension.

**Comment by lucach** [comment]
Result of the investigation:
- with our current encoder (Pillow), APNG files are both significantly bigger in size and slower to produce
- macOS deals poorly with files with files having the `.apng`: Safari refuses to visualize them even if you try to explicitly load the `file://`, unless you change the extension to `.png` (!). I haven't checked other OSes.

I'd say we do not proceed with this right now, but let's keep the option in the back of our minds for the future.
