### ISSUE TITLE
Improved debug mark rendering

### ISSUE THREAD

**Issue by hauswirth** [LuCEresearchlab/pytamaro#41]
I'd like to bring up an issue with respect to the debug marks produced by `show_graphics` that has been bugging me for a while:

![CleanShot 2024-11-26 at 11 18 59@2x](https://github.com/user-attachments/assets/b96e07aa-e285-4457-963b-c2da3c93debc)

Could we replace the rendering of these debug marks (bounding box, the nine potential pinning positions related to the bounding box, and the current pinning position) with debug marks in the style used in JTamaro (and existing vector graphics programs)?

![CleanShot 2024-11-26 at 11 20 17@2x](https://github.com/user-attachments/assets/96248d2a-54ba-436f-b95d-7ae429f9aec2)

The reasons:

- The current PyTamaro debug marks look very similar in style to normal PyTamaro graphics. I designed the JTamaro debug marks to look different than most graphics one would output.
- The current PyTamaro debug marks look very different from the corresponding marks in graphics programs (Illustrator, Affinity Designer, Inkscape, ...). I designed the JTamaro debug marks to look like those in such graphics programs, to capitalize not only on the user's familiarity, but also on the (probably) user research the developers of such programs put in to determine how to distinguish the meta-information (i.e., selection marks) from the actual graphics.

Here are examples from various graphics programs:

Affinity Designer:

![CleanShot 2024-11-26 at 11 22 38@2x](https://github.com/user-attachments/assets/692fa4dd-87ca-4a28-a089-f31b45db42d3)

Microsoft PowerPoint:

![CleanShot 2024-11-26 at 11 23 53@2x](https://github.com/user-attachments/assets/a1da2edd-8f5d-4420-919c-153aa9385c23)

Figma:

![CleanShot 2024-11-26 at 11 27 21@2x](https://github.com/user-attachments/assets/b312c2f6-6065-4d3e-a70b-e06536b86964)

**Comment by lucach** [comment]
Proposed re-design:
- control points à la Affinity
- pin indicator à la JTamaro
- 1px border
- control points and indicator scaled with the log of the graphic's area

`triangle(400, 300, 30, red)`

![image](https://github.com/user-attachments/assets/1f381ea0-30b9-4254-a658-63313a0489ef)

`rectangle(50, 50, blue)`

![image](https://github.com/user-attachments/assets/1bc5685e-bb18-429d-90e1-35545a78da96)

`rectangle(1000, 1000, black)`

![image](https://github.com/user-attachments/assets/0ac14a3a-8a1e-48d0-b406-3bc902d884aa)

**Comment by hauswirth** [comment]
In my opinion this is a clear improvement.

I'm not sure about the log; I'd keep it constant, at the smallest size. I haven't seen a tool that scales the handles based on the size of the selected shape. I believe the handles should "disappear into the background" for the user; users should be able to easily visually filter out the handles and reason just about the graphic. Like you wear glasses, and filter out the frame that is constantly in your vision. And I think that's easiest if they are constant/they always look exactly the same. But maybe you have a scenario where a fixed handle size is worse than a handle size that depends on the graphic size?

**Comment by lucach** [comment]
> I'd keep it constant, at the smallest size.

Alright (small indicators may still be too big for tiny graphics and very small for huge graphics, but those are hard to deal with anyway, not our primary target, and I like the predictability of a fixed-size design). 

New debug design in https://github.com/LuCEresearchlab/pytamaro/commit/42eea88920b2dd3aa359da601d75aba784e9d491 and released as part of pytamaro 1.1.0.
