### ISSUE TITLE
circular_sector should work differently for radius 0 and for angles 0 and 360

### ISSUE THREAD

**Issue by hauswirth** [LuCEresearchlab/pytamaro#5]
I suggest to change the behavior of `circular_sector(radius, angle, color)` as follows:

`circular_sector(0, angle, color)` should produce the same as `empty_graphic()`.

`circular_sector(radius, 0, color)` should produce the same as `empty_graphic()`.

`circular_sector(radius, 360, color)` should produce the same as `ellipse(2*radius, 2*radius, color)`.

**Comment by Fabio11111999** [comment]
Should be fixed in the next pull request.

**Comment by lucach** [comment]
Addressed in https://github.com/LuCEresearchlab/pytamaro/commit/a84334b608ae2a0ad1209a6f3442086f9626e273, but note that `circular_sector(radius, 0, color)` produces a graphic of size radius x 0, which has no area but is not equivalent to `empty_graphic()`.
