### ISSUE TITLE
Pinning position of circular_sector should be the center of circle

### ISSUE THREAD

**Issue by hauswirth** [LuCEresearchlab/pytamaro#8]
Right now it's in the midpoint of the bounding box of the sector. This leads to the "bouncy pacman problem", and it also makes implementing a pie chart (where a pie segment could be any angle, also more than 90 degrees) unreasonably complicated.

I recommend setting the pinning position of `circular_sector` to the center of the circle (independent of how small the angle of the sector is).

**Comment by Fabio11111999** [comment]
Should be fixed in the next pull request

**Comment by lucach** [comment]
Let's not forget to add to the documentation the general principle (in the center of the bounding box), as well as the special cases (text, circular sector, triangle, ...).
