### ISSUE TITLE
Better error message for show_graphic

### ISSUE THREAD

**Issue by hauswirth** [LuCEresearchlab/pytamaro#9]
Calling `show_graphic(None)` leads to a confusing error message:

```
AttributeError: 'NoneType' object has no attribute 'is_empty_graphic'
```

While such a call is a type error, and ideally is caught by a static type checker, the situation occurs frequently in exercises where functions are not yet implemented (and to be implemented by students) and have `pass` as a body. Thus, this situation should cause an error message that is much more intuitive to students, e.g., that `show_graphic` needs to be called with an argument of type `Graphic`, but that it has been called with `None` (and a hint that there might be a function that should return a Graphic but that does not actually do so).

**Comment by Fabio11111999** [comment]
I'll fix it and add it to the next pull request. But honestly, I don't think that the hint adds much information.

**Comment by lucach** [comment]
Given our special educational target, one question is whether we should manually raise an error for any function that expects to receive a parameter of type `Graphic` but instead gets an object of another type (not only `NoneType`).

**Comment by lucach** [comment]
e7ed5dcf23b214118d322f513ae2bce43f5781b4 introduces checks for types and sensible values for the parameters of the exposed functions.

Error messages refer to the names of the parameters and are localized, e.g.:

```python
>>> from pytamaro import *
>>> show_graphic(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lucach/repos/pytamaro/pytamaro/io.py", line 45, in show_graphic
    check_graphic(graphic)
  File "/Users/lucach/repos/pytamaro/pytamaro/graphic_utils.py", line 77, in check_graphic
    check_type(graphic, Graphic, parameter_name)
  File "/Users/lucach/repos/pytamaro/pytamaro/graphic_utils.py", line 54, in check_type
    raise TypeError(translate("INVALID_TYPE",
TypeError: Invalid type for parameter graphic: expected Graphic, got NoneType
```

```python
>>> from pytamaro.it import *
>>> settore_circolare(100, -1, rosso)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lucach/repos/pytamaro/pytamaro/it/primitives.py", line 76, in settore_circolare
    return circular_sector(raggio, angolo, colore)
  File "/Users/lucach/repos/pytamaro/pytamaro/primitives.py", line 87, in circular_sector
    check_angle(angle, 0, 360)
  File "/Users/lucach/repos/pytamaro/pytamaro/graphic_utils.py", line 26, in check_angle
    check_range(angle, lower_bound, upper_bound, "angle")
  File "/Users/lucach/repos/pytamaro/pytamaro/graphic_utils.py", line 101, in check_range
    raise ValueError(translate("INVALID_RANGE",
ValueError: Valore per il parametro angolo fuori dall'intervallo consentito [0, 360]
```

We're currently using standard Python exceptions, which means that the entire traceback gets printed as usual and our custom error message is shown in the last line.
